repos:


- repo: https://github.com/ambv/black
  # Black version.
  rev: 23.3.0
  hooks:
    - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.265'
  hooks:
    - id: ruff
