name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "*.md"
      - "docs/**"

jobs:
  CI:
    uses: nebuly-ai/nebuly-sdk/.github/workflows/.ci-template.yaml@main

  code-quality:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run code quality check
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
